### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by Cyberlane** [kinbiko/jisho-alfred#1]
macOS 12.4
Alfred 5.0.3
go version go1.19.1 darwin/amd64

Typing the initial `ji` works:

![image](https://user-images.githubusercontent.com/1614416/196279031-ca829661-0598-407d-ba61-e6b000b9a371.png)

However, no matter what I try to search for, instead of showing results it goes `fetching results` to this:

![image](https://user-images.githubusercontent.com/1614416/196279189-669cbc65-20c7-48ec-8aab-436324858da7.png)

Is there anything extra I need to be doing to get this running? Or perhaps some way I can debug it?

**Comment by kinbiko** [comment]
Thanks for reporting!

This plugin (kind of naively, I grant you) assumes that the binary will be located at `~/go/bin/jisho-alfred`. Can you confirm that the binary is installed in this location? If you've changed your `GOBIN` env variable for example, this would result in the behaviour you're seeing.

You can fix this by editing the `ji` and `じ` "Script Filter"s in the Jisho.org workflow in Alfred to point to whatever the path is on your system.

If this doesn't solve your problem you can debug this workflow on your system by clicking this icon in the top right of the Jisho.org workflow screen inside Alfred.
 
<img width="33" alt="image" src="https://user-images.githubusercontent.com/8797880/196305371-8ee9519c-d55e-4883-8b03-0615169f437d.png">

Let me know what output you're seeing from the debug logs if my above tips don't solve your issue.

PRs to update the documentation/script logic when/if you discover the underlying issue are welcome! 🙇

**Comment by Cyberlane** [comment]
That was indeed the problem and the little debugger was helpful.

I've changed the config to look like this, and it works for me. Not super ideal to source each time, but thankfully my zsh config is extremely lean.

```zsh
query=$1

source ~/.zshrc
"${GOPATH}/bin/jisho-alfred" $query
```

**Comment by Cyberlane** [comment]
I will look into it a bit further when I have some time, but I am thinking maybe doing an initial check if the `GOPATH` or `GOBIN` env are set, if they are not, calling the source on `.zshrc` and then checking again. Once data is found, storing the result in the settings file (see here: https://alfred-workflow.readthedocs.io/en/latest/user-manual/persistent-data.html#storing-data).

And on further tries, simply reading from the settings file and not checking anything else.

As for the failure path, perhaps return a hard coded result item which simply states that the package could not find the `GOPATH` or `GOBIN`, making it a bit more clear what's going wrong :)

**Comment by Cyberlane** [comment]
@kinbiko not exactly how I imagined it to be, but here's the result and it works, feel free to test it out.

```zsh
query=$1

if [[ -z $GO_BIN_CACHE_PATH ]]; then
  PATH_CACHE="$HOME"/.go_path
else
  PATH_CACHE="$GO_BIN_CACHE_PATH"
  if [[ -z "$PATH_CACHE" ]]; then
    . "$PATH_CACHE"
    export PATH
  fi
fi

get_gobin_path() {
  source "${HOME}/.zshrc"
  if [[ -z "$GOBIN" ]]; then
    echo "$GOBIN" > "$PATH_CACHE"
  elif [[ -z "$GOPATH" ]]; then
    echo "${GOPATH}/bin" > "$PATH_CACHE"
  fi
}

set_path() {
  if [[ -z "$PATH_CACHE" ]]; then
    . "$PATH_CACHE"
  else
    get_gobin_path
    . "$PATH_CACHE"
  fi

  export PATH
}

has_jisho() {
  command -v jisho-alfred >/dev/null 2>&1
}

if ! has_jisho; then
  set_path

  # Retry by deleting cache
  if ! has_jisho; then
    rm "$PATH_CACHE"
    set_path
  fi
fi

if has_jisho; then
  jisho-alfred $query
fi
```

If a `GO_BIN_CACHE_PATH` variable is passed, the cached path is stored there, otherwise a file is created in home named `.go_path` which will store the result. So if the command is not found, we source the `.zshrc` and then check first for the `$GOBIN`, else `$GOPATH` (and append /bin).

Now if you want to show an error, you could modify your go script to display a single result with the error when a specific query command is passed in, for example `_gobin_notfound` (or whatever else is unlikely to be searched for) and then change the last 3 lines of the above script to this:

```zsh
if has_jisho; then
  jisho-alfred $query
else
  jisho-alfred _gobin_notfound
fi
```

Since this is all embedded within the workflow file which is rather large, I didn't make it as a PR. But of course if you prefer a PR, I can open one up a bit later (got a few other things to do for my client first).

**Comment by Cyberlane** [comment]
I was clearly half asleep when I wrote that last bit... you can't call it for errors because the whole issue is you can't call it 😅 I'll see a bit later if I can make an example echo for an error.
